FROM node:23
WORKDIR /srv

ARG COOKIE_SECRET
ARG PASSWORD
ARG DATABASE_CONNECT_URI

ENV PORT=80
ENV COOKIE_SECRET=${COOKIE_SECRET:-"SECRET"}
ENV PASSWORD=${PASSWORD:-"PASSWORD"}
ENV DATABASE_CONNECT_URI=${DATABASE_CONNECT_URI:-"mongodb://localhost:27017"}

EXPOSE 80

COPY . .
RUN npm install
RUN npm install -g shx

CMD npm run start
