version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    container_name: redirects_db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME:-redirects}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_ACCOUNT:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-secret}
      - MONGO_INITDB_USERNAME=${MONGO_USER_ACCOUNT:-user}
      - MONGO_INITDB_PASSWORD=${MONGO_USER_PASSWORD:-secret}
    volumes:
      - ./mongodb-init.sh:/docker-entrypoint-initdb.d/mongodb-init.sh:ro
      - ./mongodb-volume:/data/db
  api:
    depends_on:
      - mongodb
    image: samjhirst/redirects
    build:
      context: .
    container_name: redirects_api
    environment:
      - COOKIE_SECRET=${COOKIE_SECRET:-SECRET}
      - DATABASE_CONNECT_URI=mongodb://${MONGO_USER_ACCOUNT:-user}:${MONGO_USER_PASSWORD:-secret}@mongodb/${MONGO_DATABASE_NAME:-redirects}
      - PASSWORD=${PASSWORD:-PASSWORD}
    ports:
      - 127.0.0.1:${PORT:-80}:80
